@startuml

actor HR as "Global Stat"

rectangle Database

rectangle "Language Data" {
    usecase UC4 as "Get number of
    people who speak
    Chinese, english,
    Hindi, Spanish and Arabic"

    usecase UCa as "Print ranking
    of cities"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database

}

@enduml