@startuml

actor HR as "Analyst"

rectangle Database

rectangle "World Data" {
    usecase UC4 as "Get specific number of
    cities populations in a specific
    place in decending order"

    usecase UCa as "Print cities"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml